Repository OpenAPITools/openapi-diff, pull requests merged in 2021-12, with the labels that each got.

#300 Enable reproducible builds
  pom.xml
Labels: enhancement

#301 Skip Git hook repository check to enable build without `.git`
  pom.xml
Labels: bug

#307 Migrate from Log4j 1.2.x to Logback
  cli/pom.xml
  cli/src/main/java/org/openapitools/openapidiff/cli/Main.java
  cli/src/main/resources/log4j.properties
  cli/src/main/resources/logback.xml
  pom.xml
Labels: enhancement, dependencies

#302 Exclude null properties when rendering JSON
  core/src/main/java/org/openapitools/openapidiff/core/output/JsonRender.java
Labels: enhancement

#308 Remove dependency on commons-httpclient
  core/pom.xml
  core/src/main/java/org/openapitools/openapidiff/core/output/ConsoleRender.java
  core/src/main/java/org/openapitools/openapidiff/core/output/HttpStatus.java
  core/src/main/java/org/openapitools/openapidiff/core/output/MarkdownRender.java
  pom.xml
Labels: enhancement, dependencies

#311 Use SLF4J commons-logging bridge
  core/pom.xml
  pom.xml
Labels: enhancement, dependencies
