Repository OpenAPITools/openapi-diff, pull requests merged in 2021-11, with the labels that each got.

#278 feat: add a maven plugin
  README.md
  maven/pom.xml
  maven/src/main/java/org/openapitools/openapidiff/maven/ApiChangedException.java
  maven/src/main/java/org/openapitools/openapidiff/maven/BackwardIncompatibilityException.java
  maven/src/main/java/org/openapitools/openapidiff/maven/OpenApiDiffMojo.java
  maven/src/test/java/org/openapitools/openapidiff/maven/OpenApiDiffMojoTest.java
  maven/src/test/resources/newspec.yaml
  maven/src/test/resources/oldspec.yaml
  pom.xml
Labels: enhancement

#280 Add GitHub workflow for building Docker image
  .github/workflows/docker.yml
Labels: enhancement

#286 Integrate building Docker image in release workflow
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: enhancement

#287 Change packaging to maven-plugin
  maven-example/pom.xml
  maven/pom.xml
  pom.xml
Labels: bug

#290 Ignore Maven dependencies in Dependabot
  .github/dependabot.yml
Labels: dependencies, java
