Repository OpenAPITools/openapi-diff, pull requests merged in 2022-03, with the labels that each got.

#314 upgrade m-release-p: outputTimestamp auto-update
  pom.xml
Labels: dependencies, java

#306 Equivalent paths with overloaded parameters are supported
  core/src/main/java/org/openapitools/openapidiff/core/compare/PathsDiff.java
  core/src/test/java/org/openapitools/openapidiff/core/ParametersOverloadingTest.java
  core/src/test/resources/parameters_overloading.yaml
  core/src/test/resources/parameters_overloading_2.yaml
Labels: enhancement

#331 Fix stackoverflow in recursive definitions
  core/src/main/java/org/openapitools/openapidiff/core/output/MarkdownRender.java
  core/src/test/java/org/openapitools/openapidiff/core/MarkdownRenderTest.java
  core/src/test/resources/recursive_new.yaml
  core/src/test/resources/recursive_old.yaml
Labels: bug
